---
title: "Jacob Earl's Cover Letter (CL)"
format: docx
---

Dear Hiring Manager,

I am writing to express my strong interest in the Associate Principal Scientisst, Outcomes Research, Hematology position at Merck. With a Doctor of Pharmacy from the University of Utah College of Pharmacy and a Master of Science in Health Economics and Outcomes Research from the University of Washington CHOICE Institute, I bring a unique blend of clinical expertise and advanced data analytics skills to support your value and evidence research with ADECTRIS and ELREXFIO.


In my current role at Bayer as a Post-Doctoral Fellow on the HEOR & data analytics team, I have many advanced skills that I would like to contribute to your Hematology team. I have conceptualized and designed multiple Real-World Evidence (RWE) studies — largely supporting the launch of Kerendia — using claims and EHR databases. I assessed data sets for feasibility and monitored research methodologies to ensure appropriate and timely study execution. Additionally, I reviewed various economic models and presented their validity and utility for different audiences. I believe it is my professional responsibility to be anxiously engaged in research and provide precise and effective insights in all my communications. I have been recognized for these specific skills and hope to be able to contribute them to your Hematology team.


My academic and professional journey has provided valuable insights into various facets of the healthcare industry that help me generate impactful research. I have clinical experience in a research hospital and payor experience evaluating claim appeals and presenting coverage criteria to P&T committees. With publications in Markov models, umbrella reviews, and my latest submission of a RWE study, I have demonstrated my ability to translate complex data into impactful research.


I am particularly drawn to this position to develop my skills in a large pharmaceutical company where I can have an impact in the hematology space. I am confident that my background in health economics research, coupled with my clinical/payor insights and robust analytical capabilities, would allow me to make a significant contribution to your team.


Thank you for considering my application. Please feel free to contact me at (801) 608-5538 or via email at jake.c.earl@outlook.com to arrange a conversation.


Sincerely,

Jake Earl